import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const ttNorms = localFont({
  src: [
    {
      path: './fonts/TTNorms-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/TTNorms-Medium.woff2',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/TTNorms-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
  ],
})

export const metadata: Metadata = {
  title: "Checkout",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ttNorms.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
